from abc import ABC, abstractmethod


class Solution(ABC):
    def __init__(self, repr=None):
        # If no representation is given, initialize one at random.
        if repr is None:
            repr = self.random_initial_representation()

        # If representation is provided as a bit string, normalize to list[int].
        if isinstance(repr, str):
            repr = [int(c) for c in repr]

        # Cache fitness to avoid recomputation in deterministic fitness functions.
        self._fitness = None
        self.repr = repr

    def __repr__(self):
        return str(self.repr)

    @abstractmethod
    def fitness(self):
        pass

    @abstractmethod
    def random_initial_representation(self):
        pass

    @abstractmethod
    def with_repr(self, new_repr):
        """Return a new instance with the given representation."""
        pass

    def get_bestneighbor(self):
        """Return the best element from the neighborhood generated by get_neighbors()."""
        neighborhood = self.get_neighbors()
        bestneigh = neighborhood[0]
        bestfitness = bestneigh.fitness()

        for neighb in neighborhood[1:]:
            neighbfitness = neighb.fitness()
            if neighbfitness < bestfitness:
                bestneigh = neighb
                bestfitness = neighbfitness
        return bestneigh
